#!/bin/bash

BOOTSTRAP_DIR=~/.config/yadm/bootstrap.d

# Because Git submodule commands cannot operate without a work tree, they must
# be run from within $HOME (assuming this is the root of your dotfiles)
cd "$HOME" || exit
echo "Init submodules"
yadm submodule update --recursive --init

# If display is present
if [[ -n "$DISPLAY" || -n "$WAYLAND_DISPLAY" ]]; then
    $BOOTSTRAP_DIR/install-bins.sh display
    $BOOTSTRAP_DIR/install-packages.sh display
    # IF sway
    if [[ "$XDG_SESSION_DESKTOP" == "sway" ]]; then
        $BOOTSTRAP_DIR/install-packages.sh sway
    fi
fi

# Install on any computer
$BOOTSTRAP_DIR/install-bins.sh nodisplay
$BOOTSTRAP_DIR/install-packages.sh nodisplay
