[colors.bright]
black = "0x888888"
blue = "0x0f75bd"
cyan = "0x37c3d6"
green = "0x86df5d"
magenta = "0x9e5e83"
red = "0xd64937"
white = "0xf9f9f9"
yellow = "0xfdd75a"

[colors.cursor]
cursor = "#eeeeee"
text = "CellBackground"

[colors.normal]
black = "0x555555"
blue = "0x0d68a8"
cyan = "0x288e9c"
green = "0x61bc3b"
magenta = "0x744560"
red = "0xc13220"
white = "0xa2a2a2"
yellow = "0xf3b43a"

[colors.primary]
background = "0x181818"
foreground = "0xd1d1d1"
